name: Build Image

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "README.md"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dockerhub login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD_JINLI }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME_JINLI }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin hub.jinli.plus
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build dockerfile (with push)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME_JINLI }}
        run: |
          docker buildx build \
          --platform=linux/amd64 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag hub.jinli.plus/jinlicode/redis:5.0.9
